# Dockerfile.frontend

FROM node:24-slim AS builder

WORKDIR /app
COPY frontend/ .

# commands needed to run the frontend sveltekit
RUN npm install && npm run build

# serve built static files with Nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
