# Dockerfile.frontend

# Build the frontend
FROM node:24-slim AS builder

WORKDIR /app
COPY frontend/ .
RUN npm install && npm run build

# Serve the built static files with Nginx
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
