# Dockerfile.backend
FROM python:3.12-slim

# working directory
WORKDIR /app

# requirements.txt
COPY requirements.txt .

# install all dependencies
RUN pip install --no-cache-dir -r requirements.txt

# backend flask rest api (app.py) code
COPY backend/ ./

# env variables for flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

EXPOSE 5000

# start flask server
CMD ["flask", "run"]
